// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcMovie.Data;

#nullable disable

namespace BTLNHOM11.Migrations
{
    [DbContext(typeof(MvcMovieContext))]
    [Migration("20230528170501_chucvu")]
    partial class chucvu
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("BTLNHOM11.Models.chucvu", b =>
                {
                    b.Property<string>("idcv")
                        .HasColumnType("TEXT");

                    b.Property<string>("motacv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tencv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("idcv");

                    b.ToTable("chucvu");
                });
#pragma warning restore 612, 618
        }
    }
}
