// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcMovie.Data;

#nullable disable

namespace BTLNHOM11.Migrations
{
    [DbContext(typeof(MvcMovieContext))]
    [Migration("20230528185124_hoadon")]
    partial class hoadon
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("BTLNHOM11.Models.chucvu", b =>
                {
                    b.Property<string>("idcv")
                        .HasColumnType("TEXT");

                    b.Property<string>("motacv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tencv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("idcv");

                    b.ToTable("chucvu");
                });

            modelBuilder.Entity("BTLNHOM11.Models.hoadon", b =>
                {
                    b.Property<string>("mahd")
                        .HasColumnType("TEXT");

                    b.Property<string>("soluongban")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tenkh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tensp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("tgban")
                        .HasColumnType("TEXT");

                    b.HasKey("mahd");

                    b.HasIndex("tenkh");

                    b.HasIndex("tensp");

                    b.ToTable("hoadon");
                });

            modelBuilder.Entity("BTLNHOM11.Models.khachhang", b =>
                {
                    b.Property<string>("makh")
                        .HasColumnType("TEXT");

                    b.Property<string>("diachikh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("sdtkh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tenkh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("makh");

                    b.ToTable("khachhang");
                });

            modelBuilder.Entity("BTLNHOM11.Models.nhacungcap", b =>
                {
                    b.Property<string>("mancc")
                        .HasColumnType("TEXT");

                    b.Property<string>("diachincc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("emailncc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("sdtncc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tenncc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("mancc");

                    b.ToTable("nhacungcap");
                });

            modelBuilder.Entity("BTLNHOM11.Models.nhanvien", b =>
                {
                    b.Property<string>("manv")
                        .HasColumnType("TEXT");

                    b.Property<string>("diachinv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("emailnv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("gtnv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ngaylamnv")
                        .HasColumnType("TEXT");

                    b.Property<string>("nsnv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("sdtnv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tencv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tennv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("manv");

                    b.HasIndex("tencv");

                    b.ToTable("nhanvien");
                });

            modelBuilder.Entity("BTLNHOM11.Models.nhaphang", b =>
                {
                    b.Property<string>("idnh")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ngaynh")
                        .HasColumnType("TEXT");

                    b.Property<string>("soluongnh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tenncc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tensp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("idnh");

                    b.HasIndex("tenncc");

                    b.HasIndex("tensp");

                    b.ToTable("nhaphang");
                });

            modelBuilder.Entity("BTLNHOM11.Models.sanpham", b =>
                {
                    b.Property<string>("masp")
                        .HasColumnType("TEXT");

                    b.Property<string>("gia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tensp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("masp");

                    b.ToTable("sanpham");
                });

            modelBuilder.Entity("BTLNHOM11.Models.hoadon", b =>
                {
                    b.HasOne("BTLNHOM11.Models.khachhang", "khachhang")
                        .WithMany()
                        .HasForeignKey("tenkh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BTLNHOM11.Models.sanpham", "sanpham")
                        .WithMany()
                        .HasForeignKey("tensp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("khachhang");

                    b.Navigation("sanpham");
                });

            modelBuilder.Entity("BTLNHOM11.Models.nhanvien", b =>
                {
                    b.HasOne("BTLNHOM11.Models.chucvu", "chucvu")
                        .WithMany()
                        .HasForeignKey("tencv")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("chucvu");
                });

            modelBuilder.Entity("BTLNHOM11.Models.nhaphang", b =>
                {
                    b.HasOne("BTLNHOM11.Models.nhacungcap", "nhacungcap")
                        .WithMany()
                        .HasForeignKey("tenncc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BTLNHOM11.Models.sanpham", "sanpham")
                        .WithMany()
                        .HasForeignKey("tensp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("nhacungcap");

                    b.Navigation("sanpham");
                });
#pragma warning restore 612, 618
        }
    }
}
