// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcMovie.Data;

#nullable disable

namespace BTLNHOM11.Migrations
{
    [DbContext(typeof(MvcMovieContext))]
    partial class MvcMovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("BTLNHOM11.Models.chucvu", b =>
                {
                    b.Property<string>("idcv")
                        .HasColumnType("TEXT");

                    b.Property<string>("motacv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tencv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("idcv");

                    b.ToTable("chucvu");
                });

            modelBuilder.Entity("BTLNHOM11.Models.nhacungcap", b =>
                {
                    b.Property<string>("mancc")
                        .HasColumnType("TEXT");

                    b.Property<string>("diachincc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("emailncc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("sdtncc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tenncc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("mancc");

                    b.ToTable("nhacungcap");
                });

            modelBuilder.Entity("BTLNHOM11.Models.nhanvien", b =>
                {
                    b.Property<string>("manv")
                        .HasColumnType("TEXT");

                    b.Property<string>("diachinv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("emailnv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("gtnv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ngaylamnv")
                        .HasColumnType("TEXT");

                    b.Property<string>("nsnv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("sdtnv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tencv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tennv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("manv");

                    b.HasIndex("tencv");

                    b.ToTable("nhanvien");
                });

            modelBuilder.Entity("BTLNHOM11.Models.nhanvien", b =>
                {
                    b.HasOne("BTLNHOM11.Models.chucvu", "chucvu")
                        .WithMany()
                        .HasForeignKey("tencv")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("chucvu");
                });
#pragma warning restore 612, 618
        }
    }
}
